---
- name: Install prerequisites
  command: yum update -y

- name: Install dev tools
  command: yum group install "Development Tools" -y

- name: Install required system packages
  yum: name={{ item }} state=latest update_cache=yes
  loop:
    - curl
    - amazon-linux-extras
      # - ufw
      # - fail2ban
    - git
      # - ca-certificates
      # - software-properties-common
      # - python3-pip
      # - virtualenv
      # - python3-setuptools
      # - mosh # Mosh package is broken, compile from source following: https://gist.github.com/ctd/9fbd0ed5b7d9be1aa532d11a0701bae1
    - "{{ required_packages }}"

- name: Install libuv system package
  yum: name={{ item }} state=latest update_cache=yes disable_plugin=priorities
  loop:
    - libuv

- name: Make Extra packages available
  command: amazon-linux-extras install -y epel

- name: Install jemalloc
  yum:
    state: latest
    name: jemalloc
