---
- name: Install and managing rails application on EC2
  hosts: all
  become: True # Execute as root
  tasks:
    - name: Update the OS
      command: yum update
    - name: Add yarn repo to yum
      command: curl -sL https://dl.yarnpkg.com/rpm/yarn.repo -o /etc/yum.repos.d/yarn.repo
    - name: Install deps
      yum:
        state: present
        name:
          - git
          - amazon-linux-extras
          - curl
          - sqlite-devel.x86_64
            # - dirmngr
            # - redis-server # These don't seem to be available. Use managed redis? Or ubuntu
            # - redis-tools
    - name: Get Node
      command: curl --silent --location https://rpm.nodesource.com/setup_16.x | bash
      ignore_errors: true # Above script incorrectly returns non 0
    - name: Install Node
      yum:
        state: present
        name:
          - nodejs
    - name: Install yarn
      command: npm install yarn
